### ISSUE TITLE
Error: Cannot find module './lib/websocket'

### ISSUE THREAD

**Issue by merelinguist** [jxnblk/ok-mdx#5]
Followed the setup guide in the README, tried to run `mdx docs --open`, and received: `Error: Cannot find module './lib/websocket'`.

Full error:
```sh
$ mdx docs --open

----
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './lib/websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Dylan/.config/yarn/global/node_modules/ws/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by merelinguist** [comment]
Sure!

- Node: `v10.4.1`, yarn: `0.27.5`
- It was a global install
- I tried installing as a dev dependency and got the same error
- No other dependencies

I also tried using npm instead of yarn and got the same error
